# Generated by Django 5.2.8 on 2025-11-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_compra_alter_produto_quantidade_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='descricao',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='valor',
            new_name='preco_unitario',
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='valor_final',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='valor_total',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='valor_unitario',
        ),
        migrations.AlterField(
            model_name='compra',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
