# Generated by Django 5.2.8 on 2025-11-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_financeiro_rename_descricao_compra_nome_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='Financeiro',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='valor',
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
